CREATE TABLE EMPLOYEES
   (	ID NUMBER,
	NAME VARCHAR2(100),
	SURNAME VARCHAR2(100),
	DEPARTMENT_ID NUMBER,
	SALARY NUMBER,
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE,
	 CONSTRAINT CHK_SALARIO_DEPARTAMENTO CHECK (
  (department_id = 10 AND salary >= 50000) OR
  (department_id != 10 AND salary >= 30000)
) ENABLE
   ) ;

