CREATE TABLE EMPLEADOS
   (	ID NUMBER,
	NOMBRE VARCHAR2(100),
	DEPARTAMENTO_ID NUMBER,
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE,
	 CONSTRAINT FK_EMPLEADOS_DEPTOS FOREIGN KEY (DEPARTAMENTO_ID)
	  REFERENCES DEPARTAMENTOS (ID) ENABLE
   ) ;

